//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubSearch.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubSearch.Resources.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Download.
        /// </summary>
        public static string Data__Download {
            get {
                return ResourceManager.GetString("Data__Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp;amp; _Close.
        /// </summary>
        public static string Data_Download__Close {
            get {
                return ResourceManager.GetString("Data_Download__Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp;amp; _Play.
        /// </summary>
        public static string Data_Download__Play {
            get {
                return ResourceManager.GetString("Data_Download__Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the video subtitle [{0}]....
        /// </summary>
        public static string Data_Downloading_video_subtitle {
            get {
                return ResourceManager.GetString("Data_Downloading_video_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download subtitle: .
        /// </summary>
        public static string Data_Failed_download_subtitles {
            get {
                return ResourceManager.GetString("Data_Failed_download_subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching title could be found for: .
        /// </summary>
        public static string Data_No_matching_title_for {
            get {
                return ResourceManager.GetString("Data_No_matching_title_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subtitle found for: .
        /// </summary>
        public static string Data_No_subtitle_for {
            get {
                return ResourceManager.GetString("Data_No_subtitle_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for video subtitle....
        /// </summary>
        public static string Data_Searching_video_subtitle {
            get {
                return ResourceManager.GetString("Data_Searching_video_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for video title....
        /// </summary>
        public static string Data_Searching_video_title {
            get {
                return ResourceManager.GetString("Data_Searching_video_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the matching video title.
        /// </summary>
        public static string Data_Select_matching_video_title {
            get {
                return ResourceManager.GetString("Data_Select_matching_video_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the subtitle to download [{0}]....
        /// </summary>
        public static string Data_Select_subtitle {
            get {
                return ResourceManager.GetString("Data_Select_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download subtitles.
        /// </summary>
        public static string ShellExtension_CreateMenu_Download_dir_subtitle {
            get {
                return ResourceManager.GetString("ShellExtension_CreateMenu_Download_dir_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download subtitle.
        /// </summary>
        public static string ShellExtension_CreateMenu_Download_subtitle {
            get {
                return ResourceManager.GetString("ShellExtension_CreateMenu_Download_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download subtitle (Lucky).
        /// </summary>
        public static string ShellExtension_CreateMenu_Download_subtitle_lucky {
            get {
                return ResourceManager.GetString("ShellExtension_CreateMenu_Download_subtitle_lucky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process request. Please reinstall the application or try again from the Windows Shell&apos;s context menu!.
        /// </summary>
        public static string ShellExtension_Failed_process_request {
            get {
                return ResourceManager.GetString("ShellExtension_Failed_process_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles downloads were completed successfully!.
        /// </summary>
        public static string ShellExtension_Subtitles_downloaded_successfully {
            get {
                return ResourceManager.GetString("ShellExtension_Subtitles_downloaded_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
